### PR TITLE
Updated versions of requests, beautifulsoup4, and pydantic

### PR DESCRIPTION
**Pull request by alexander-cummings**

### CODE REVIEW

**Comment by AlexandreSenpai** [comment]
Hello @alexander-cummings.

Some tests are failing, could you check the changes in order to get all the tests passing?

Thanks for your contrib!

**Comment by alexander-cummings** [comment]
@AlexandreSenpai Hmm... I tried running the same tests on the master branch, and they seem to be failing as well for me. Could you please try rerunning the tests on the current master branch and see if they succeed for you?

**Comment by alexander-cummings** [comment]
Hi, @AlexandreSenpai. Did you have a chance to run the tests on the master branch and check if the same issue occurs there for you as well?

**Comment by alexander-cummings** [comment]
Hi, @AlexandreSenpai. Wanted to check in again. Thanks!

**Comment by AlexandreSenpai** [comment]
Hello, @alexander-cummings. I'm going to check this night. (GMT-3)

**Comment by alexander-cummings** [comment]
Thanks for the update! Please let me know. @AlexandreSenpai

**Comment by AlexandreSenpai** [comment]
Thanks for your contrib. Your PR has been accepted and merged!

**Pull request merged**
